# Generated by Django 3.1.7 on 2021-05-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210430_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='image',
            field=models.ImageField(null=True, upload_to='content/account'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
