# Generated by Django 3.1.7 on 2021-04-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='content/categories')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('image', models.ImageField(upload_to='content/exhibition')),
                ('date', models.DateField(default='0000-00-00')),
                ('time', models.TimeField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('address', models.CharField(max_length=250)),
                ('weekday', models.IntegerField(null=True)),
                ('categories', models.ManyToManyField(to='main.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('image', models.ImageField(upload_to='content/pictures')),
                ('categories', models.ManyToManyField(to='main.Categories')),
            ],
        ),
        migrations.DeleteModel(
            name='Main',
        ),
    ]
