# Generated by Django 3.1.7 on 2021-04-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210404_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(upload_to='content/categories'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.ImageField(upload_to='content/pictures'),
        ),
    ]
