# Generated by Django 3.1.7 on 2021-04-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210415_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitions',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='time',
            field=models.TimeField(),
        ),
    ]
