# Generated by Django 3.1.7 on 2021-04-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210415_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitions',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
