# Generated by Django 3.1.7 on 2021-04-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210415_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitions',
            name='image',
            field=models.ImageField(null=True, upload_to='content/exhibition'),
        ),
    ]
