# Generated by Django 3.1.7 on 2021-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210415_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitions',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='image',
            field=models.ImageField(upload_to='content/exhibition'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='time',
            field=models.TimeField(),
        ),
    ]
