# Generated by Django 3.1.7 on 2021-04-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210416_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('birtday', models.DateField(null=True)),
                ('nick_name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='content/account')),
            ],
        ),
    ]
