# Generated by Django 3.1.7 on 2021-04-17 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='birtday',
            new_name='birthday',
        ),
    ]
