# Generated by Django 3.1.7 on 2021-04-18 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210417_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ManyToManyField(to='main.Accounts')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pictures')),
            ],
        ),
    ]
